[versions]
kotlin = "1.8.0"
shadow = "8.1.1"
log4j = "2.20.0"
protobuf = "3.25.2"
protobufPlugin = "0.9.4"
grpcVersion = "1.61.0"
grpcKotlinVersion = "1.4.1"

[libraries]
kotlinJvm = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
log4jCore = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4jApi = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4jSlf4j = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }
protobuf = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
grpcStub = { module = "io.grpc:grpc-stub", version.ref = "grpcVersion" }
grpcKotlinStub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpcKotlinVersion" }
grpcProtobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpcVersion" }
grpcNettyShaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpcVersion" }

[bundles]
log4j = [
    "log4jCore",
    "log4jApi",
    "log4jSlf4j"
]
proto = [
    "protobuf",
    "grpcStub",
    "grpcKotlinStub",
    "grpcProtobuf",
    "grpcNettyShaded"
]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }